---
- name: Play nginx-configuration
  hosts: webservers
  become: true
  
  tasks:
    - name: Install Nginx web server
      become: true
      apt:
        name: nginx
        state: latest 
        update_cache: yes
        
    - name: Enable Nginx HTTP
      become: true
      shell: "sudo ufw allow 'Nginx HTTP'"

    - name: Install PHP
      become: true
      apt:
        name: php
        state: latest
        update_cache: yes

    - name: Install PHP FPM
      become: true
      apt:
        name: php-fpm
        state: latest
        update_cache: yes
        
    - name: Remove apache2 service from webservers
      apt:
        name: apache2
        state: absent

    - name: copy the nginx config file to site.cfg
      copy:
        src: ~/site.cfg
        dest: /etc/nginx/sites-available/site.cfg
      
    - name: copy the nginx config file to default
      copy:
        src: ~/site.cfg
        dest: /etc/nginx/sites-available/default
 
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/site.cfg
        remote_src: true
        dest: /etc/nginx/sites-enabled/default
        state: link
      
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: copy the content of the web site
      copy:
        src: ~/index.php
        dest: /var/www/html/index.php

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart php-fpm
      service:
        name: php-fpm
        state: restarted

