---
- name: Play nginx-configuration
  hosts: webservers
  become: true
  
  tasks:
    - name: Install Nginx web server
      become: true
      apt:
        name: nginx
        state: latest 
        
    - name: start nginx
      service:
        name: nginx
        state: started

    - name: Install PHP
      become: true
      apt:
        name: php
        state: latest

    - name: Install PHP FPM
      become: true
      apt:
        name: php-fpm
        state: latest
        
    - name: Remove apache2 service from webservers
      apt:
        name: apache2
        state: absent

    - name: copy the nginx config file to site.cfg
      copy:
        src: ./site.cfg
        dest: /etc/nginx/sites-available/site.cfg
      become: yes
      
    - name: copy the nginx config file to default
      copy:
        src: ./site.cfg
        dest: /etc/nginx/sites-available/default
      become: yes

    - name: copy the content of the web site
      copy:
        src: ./index.php
        dest: /var/www/html/index.php
      become: yes

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
     
- name: Play ipv4address-configuration
  hosts: webservers
  tasks:
    - debug: var=ansible_all_ipv4_addresses
      
- name: Play haproxy-configuration
  hosts: haproxy
  remote_user: ubuntu
  become: true
  tasks:
    - name: Install haproxy service
      apt:
        name: haproxy
        state: latest     
        update_cache: yes

    - name: Update haproxy config file
      copy:
        src: ./haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      become: yes
                        
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
     
    - name: start haproxy
      service:
        name: haproxy 
        state: started


