---
- name: Play nginx-configuration
  hosts: webservers
  become: yes
  remote_user: root
  tasks:
    - name: Install Nginx web server
      become: true
      apt:
        name: nginx
        state: latest 
        
    - name: Enable Nginx HTTP
      become: true
      shell: "sudo ufw allow 'Nginx HTTP'"

    - name: Install PHP
      become: true
      apt:
        name: php
        state: latest

    - name: Install PHP FPM
      become: true
      apt:
        name: php-fpm
        state: latest
        
    - name: Remove apache2 service from webservers
      apt:
        name: apache2
        state: absent

    - name: copy the nginx config file to site.cfg
      copy:
        src: ./site.cfg
        dest: /etc/nginx/sites-available/site.cfg
      become: yes
      
    - name: copy the nginx config file to default
      copy:
        src: ./site.cfg
        dest: /etc/nginx/sites-available/default
      become: yes
 
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/site.cfg
        remote_src: true
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
      
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

    - name: copy the content of the web site
      copy:
        src: ./index.php
        dest: /var/www/html/index.php
      become: yes

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

    - name: restart php-fpm
      service:
        name: php-fpm
        state: restarted
      become: yes

